concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "pi-hitl"
  url = "https://gitlab.ecs.vuw.ac.nz/"
  token = "MKzP3ebBxAGziRqqJzLa"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
